### ISSUE TITLE
Intermittent test failure

### ISSUE THREAD

**Issue by ctrueden** [saalfeldlab/n5-viewer#43]
When running the pom-scijava melting pot, the n5-viewer_fiji component sometimes fails tests with the exception:
```
java.lang.AssertionError: could not find metadata at: /c3z1t1
	at org.junit.Assert.fail(Assert.java:89)
	at org.janelia.saalfeldlab.n5.bdv.BdvMetadataIoTests.readWriteParseTest(BdvMetadataIoTests.java:88)
	at org.janelia.saalfeldlab.n5.bdv.BdvMetadataIoTests.testMultiChannelHelper(BdvMetadataIoTests.java:186)
	at org.janelia.saalfeldlab.n5.bdv.BdvMetadataIoTests.testMultiChannel(BdvMetadataIoTests.java:149)
```
To work around this, I just rerun the CI build and it usually passes the next time. But it would be nice if this could be made more robust. Any ideas what might be going on here?

**Comment by bogovicj** [comment]
> But it would be nice if this could be made more robust. Any ideas what might be going on here?

Agreed, will investigate
